POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Post 1",
    "postType": "post",
    "slug": "post-1",
    "status": "published",
    "content": "Content 1",
    "schema": "{
        "type": "object",
        "properties": {
            "title": {
                "type": "string"
            }
        }
    }",
    "featuredImage": "https://example.com/image.jpg",
    "publishedOn": "2026-01-01",
    "tags": ["tag1", "tag2"],
    "metaOptions": [{ "key": "sidebarEnabled", "value": true }]
}