POST http://localhost:3000/tags
Content-Type: application/json

{
    "name": "Tag 4",
    "slug": "tag-4",
    "description": "Tag 4 description"
    // "schema": "Tag 1 schema",
    // "featuredImage": "Tag 1 featured image"
}